In [3]:
import numpy as np
import pandas as pd

In [4]:
csv_df = pd.read_csv("Melbourne_housing_FULL.csv")

In [5]:
from sklearn.ensemble import RandomForestRegressor

In [6]:
rf = RandomForestRegressor()

In [7]:
csv_df.head().T

0                      1  \
Suburb                    Abbotsford             Abbotsford   
Address                68 Studley St           85 Turner St   
Rooms                              2                      2   
Type                               h                      h   
Price                            NaN               1.48e+06   
Method                            SS                      S   
SellerG                       Jellis                 Biggin   
Date                       3/09/2016              3/12/2016   
Distance                         2.5                    2.5   
Postcode                        3067                   3067   
Bedroom2                           2                      2   
Bathroom                           1                      1   
Car                                1                      1   
Landsize                         126                    202   
BuildingArea                     NaN                    NaN   
YearBuilt                        NaN                    NaN   
CouncilArea       Yarra City Council     Yarra City Council   
Lattitude                   -37.8014               -37.7996   
Longtitude                   144.996                144.998   
Regionname     Northern Metropolitan  Northern Metropolitan   
Propertycount                   4019                   4019   

                                   2                      3  \
Suburb                    Abbotsford             Abbotsford   
Address              25 Bloomburg St     18/659 Victoria St   
Rooms                              2                      3   
Type                               h                      u   
Price                      1.035e+06                    NaN   
Method                             S                     VB   
SellerG                       Biggin                 Rounds   
Date                       4/02/2016              4/02/2016   
Distance                         2.5                    2.5   
Postcode                        3067                   3067   
Bedroom2                           2                      3   
Bathroom                           1                      2   
Car                                0                      1   
Landsize                         156                      0   
BuildingArea                      79                    NaN   
YearBuilt                       1900                    NaN   
CouncilArea       Yarra City Council     Yarra City Council   
Lattitude                   -37.8079               -37.8114   
Longtitude                   144.993                145.012   
Regionname     Northern Metropolitan  Northern Metropolitan   
Propertycount                   4019                   4019   

                                   4  
Suburb                    Abbotsford  
Address                 5 Charles St  
Rooms                              3  
Type                               h  
Price                      1.465e+06  
Method                            SP  
SellerG                       Biggin  
Date                       4/03/2017  
Distance                         2.5  
Postcode                        3067  
Bedroom2                           3  
Bathroom                           2  
Car                                0  
Landsize                         134  
BuildingArea                     150  
YearBuilt                       1900  
CouncilArea       Yarra City Council  
Lattitude                   -37.8093  
Longtitude                   144.994  
Regionname     Northern Metropolitan  
Propertycount                   4019

In [8]:
feat_df = csv_df.drop('Price', axis=1)

In [9]:
csv_df.shape


(34857, 21)

In [10]:
feat_df.shape


(34857, 20)

In [11]:
csv_df['Price']

0              NaN
1        1480000.0
2        1035000.0
3              NaN
4        1465000.0
5         850000.0
6        1600000.0
7              NaN
8              NaN
9              NaN
10        941000.0
11       1876000.0
12             NaN
13             NaN
14       1636000.0
15       1000000.0
16        745000.0
17        300000.0
18       1097000.0
19        542000.0
20             NaN
21        760000.0
22        481000.0
23        700000.0
24       1350000.0
25        750000.0
26       1985000.0
27        500000.0
28       1172500.0
29        441000.0
           ...    
34827    1096000.0
34828     900000.0
34829          NaN
34830    1150000.0
34831     675000.0
34832     689000.0
34833     936000.0
34834          NaN
34835          NaN
34836    1400000.0
34837    2020000.0
34838     450000.0
34839     475000.0
34840     520000.0
34841     940000.0
34842    1400000.0
34843     830000.0
34844     440000.0
34845          NaN
34846     630000.0
34847     500000.0
34848     62

In [12]:
y = csv_df['Price'].values

In [13]:
y

array([     nan, 1480000., 1035000., ...,  705000., 1140000., 1020000.])

In [14]:
y.shape

(34857,)

In [15]:
csv_df.isnull()

Suburb  Address  Rooms   Type  Price  Method  SellerG   Date  Distance  \
0       False    False  False  False   True   False    False  False     False   
1       False    False  False  False  False   False    False  False     False   
2       False    False  False  False  False   False    False  False     False   
3       False    False  False  False   True   False    False  False     False   
4       False    False  False  False  False   False    False  False     False   
5       False    False  False  False  False   False    False  False     False   
6       False    False  False  False  False   False    False  False     False   
7       False    False  False  False   True   False    False  False     False   
8       False    False  False  False   True   False    False  False     False   
9       False    False  False  False   True   False    False  False     False   
10      False    False  False  False  False   False    False  False     False   
11      False    False  False  False  False   False    False  False     False   
12      False    False  False  False   True   False    False  False     False   
13      False    False  False  False   True   False    False  False     False   
14      False    False  False  False  False   False    False  False     False   
15      False    False  False  False  False   False    False  False     False   
16      False    False  False  False  False   False    False  False     False   
17      False    False  False  False  False   False    False  False     False   
18      False    False  False  False  False   False    False  False     False   
19      False    False  False  False  False   False    False  False     False   
20      False    False  False  False   True   False    False  False     False   
21      False    False  False  False  False   False    False  False     False   
22      False    False  False  False  False   False    False  False     False   
23      False    False  False  False  False   False    False  False     False   
24      False    False  False  False  False   False    False  False     False   
25      False    False  False  False  False   False    False  False     False   
26      False    False  False  False  False   False    False  False     False   
27      False    False  False  False  False   False    False  False     False   
28      False    False  False  False  False   False    False  False     False   
29      False    False  False  False  False   False    False  False     False   
...       ...      ...    ...    ...    ...     ...      ...    ...       ...   
34827   False    False  False  False  False   False    False  False     False   
34828   False    False  False  False  False   False    False  False     False   
34829   False    False  False  False   True   False    False  False     False   
34830   False    False  False  False  False   False    False  False     False   
34831   False    False  False  False  False   False    False  False     False   
34832   False    False  False  False  False   False    False  False     False   
34833   False    False  False  False  False   False    False  False     False   
34834   False    False  False  False   True   False    False  False     False   
34835   False    False  False  False   True   False    False  False     False   
34836   False    False  False  False  False   False    False  False     False   
34837   False    False  False  False  False   False    False  False     False   
34838   False    False  False  False  False   False    False  False     False   
34839   False    False  False  False  False   False    False  False     False   
34840   False    False  False  False  False   False    False  False     False   
34841   False    False  False  False  False   False    False  False     False   
34842   False    False  False  False  False   False    False  False     False   
34843   False    False  False  False  False   False    False  False     False   
34844   False    False  False  False  

In [16]:
csv_df.isnull().shape


(34857, 21)

In [17]:
csv_df.isnull().any(axis=1)

0         True
1         True
2        False
3         True
4        False
5         True
6        False
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14       False
15        True
16        True
17        True
18       False
19        True
20        True
21        True
22        True
23        True
24       False
25       False
26        True
27        True
28        True
29        True
         ...  
34827     True
34828    False
34829     True
34830     True
34831    False
34832     True
34833     True
34834     True
34835     True
34836    False
34837    False
34838     True
34839     True
34840     True
34841     True
34842     True
34843     True
34844     True
34845     True
34846     True
34847    False
34848     True
34849    False
34850     True
34851     True
34852     True
34853    False
34854    False
34855     True
34856    False
Length: 34857, dtype: bool

In [18]:
csv_df.isnull().any(axis=0)

Suburb           False
Address          False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Date             False
Distance          True
Postcode          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude         True
Longtitude        True
Regionname        True
Propertycount     True
dtype: bool

In [128]:
rows_labeled_na = csv_df.isnull().any(axis=1)

(34857,)

In [20]:
rows_with_na = csv_df[rows_labeled_na]

In [21]:
rows_with_data = csv_df[~rows_labeled_na]

In [22]:
csv_df.shape, rows_with_na.shape, rows_with_data.shape

((34857, 21), (25970, 21), (8887, 21))

In [23]:
feat_df = rows_with_data.drop('Price', axis=1)

In [24]:
feat_df.shape

(8887, 20)

In [130]:
y = rows_with_data['Price'].values

In [131]:
y.shape

(8887,)

In [27]:
suburbs={}
feat_df['Suburb']
feat_df['Suburb'].values
for s in feat_df['Suburb'].values:
    if s not in suburbs:
        suburbs[s] = len(suburbs)

In [28]:
len(suburbs)

315

In [29]:
len(suburbs)
feat_df['Suburb'] = feat_df['Suburb'].replace(suburbs)

In [30]:
feat_df['Suburb']

2          0
4          0
6          0
11         0
14         0
18         0
24         0
25         0
30         0
32         0
35         0
37         0
38         0
42         0
43         0
44         0
49         0
51         0
56         0
57         0
58         0
59         0
61         0
63         0
66         1
67         1
68         1
70         1
71         1
72         1
        ... 
34750    181
34752    181
34756     93
34758     94
34760     94
34766     96
34771    232
34777     97
34780     97
34782    213
34784    213
34787     98
34789     98
34790     98
34791     98
34804    234
34807    100
34819    215
34820    184
34823    184
34826    124
34828    124
34831    216
34836    217
34837    103
34847    257
34849    257
34853    107
34854    107
34856    107
Name: Suburb, Length: 8887, dtype: int64

In [31]:

feat_df['Address'].astype('category')
feat_df['Address'].astype('category').cat.categories

Index(['1 Airlie St', '1 Alexander St', '1 Alma St', '1 Ann St',
       '1 Auckland St', '1 Balloan St', '1 Bardia St', '1 Barunah St',
       '1 Baxter St', '1 Bee Ct',
       ...
       '99 Kellett St', '99 Waterview Dr', '994 Waverley Rd', '9A Methven St',
       '9A Montgomery St', '9A Neptune St', '9A The Crossway',
       '9a Elizabeth St', '9a Ivan Av', '9a The Crossway'],
      dtype='object', length=8764)

In [32]:
feat_df['Type'].astype('category').cat.categories

Index(['h', 't', 'u'], dtype='object')

In [33]:
feat_df['Type'].astype('category').cat.codes

2        0
4        0
6        0
11       0
14       0
18       0
24       0
25       2
30       0
32       0
35       0
37       0
38       0
42       2
43       0
44       0
49       0
51       0
56       0
57       2
58       0
59       0
61       0
63       0
66       1
67       0
68       0
70       0
71       1
72       0
        ..
34750    0
34752    0
34756    0
34758    0
34760    0
34766    0
34771    0
34777    0
34780    0
34782    0
34784    0
34787    1
34789    0
34790    0
34791    0
34804    0
34807    0
34819    0
34820    0
34823    0
34826    0
34828    0
34831    0
34836    0
34837    0
34847    0
34849    0
34853    0
34854    1
34856    0
Length: 8887, dtype: int8

In [34]:
feat_df['Type'] = feat_df['Type'].astype('category').cat.codes

In [35]:
feat_df.head()

Suburb          Address  Rooms  Type Method SellerG       Date  Distance  \
2        0  25 Bloomburg St      2     0      S  Biggin  4/02/2016       2.5   
4        0     5 Charles St      3     0     SP  Biggin  4/03/2017       2.5   
6        0      55a Park St      4     0     VB  Nelson  4/06/2016       2.5   
11       0     124 Yarra St      3     0      S  Nelson  7/05/2016       2.5   
14       0    98 Charles St      2     0      S  Nelson  8/10/2016       2.5   

    Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt  \
2     3067.0       2.0       1.0  0.0     156.0          79.0     1900.0   
4     3067.0       3.0       2.0  0.0     134.0         150.0     1900.0   
6     3067.0       3.0       1.0  2.0     120.0         142.0     2014.0   
11    3067.0       4.0       2.0  0.0     245.0         210.0     1910.0   
14    3067.0       2.0       1.0  2.0     256.0         107.0     1890.0   

           CouncilArea  Lattitude  Longtitude             Regionname  \
2   Yarra City Council   -37.8079    144.9934  Northern Metropolitan   
4   Yarra City Council   -37.8093    144.9944  Northern Metropolitan   
6   Yarra City Council   -37.8072    144.9941  Northern Metropolitan   
11  Yarra City Council   -37.8024    144.9993  Northern Metropolitan   
14  Yarra City Council   -37.8060    144.9954  Northern Metropolitan   

    Propertycount  
2          4019.0  
4          4019.0  
6          4019.0  
11         4019.0  
14         4019.0

In [36]:
feat_df['Address'] = feat_df['Address'].astype('category').cat.codes
feat_df['Method'] = feat_df['Method'].astype('category').cat.codes
feat_df['SellerG'] = feat_df['SellerG'].astype('category').cat.codes
feat_df['CouncilArea'] = feat_df['CouncilArea'].astype('category').cat.codes
feat_df['Regionname'] = feat_df['Regionname'].astype('category').cat.codes

In [37]:
feat_df.head()

Suburb  Address  Rooms  Type  Method  SellerG       Date  Distance  \
2        0     3922      2     0       1       22  4/02/2016       2.5   
4        0     6458      3     0       3       22  4/03/2017       2.5   
6        0     6960      4     0       4      147  4/06/2016       2.5   
11       0     1374      3     0       1      147  7/05/2016       2.5   
14       0     8740      2     0       1      147  8/10/2016       2.5   

    Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt  \
2     3067.0       2.0       1.0  0.0     156.0          79.0     1900.0   
4     3067.0       3.0       2.0  0.0     134.0         150.0     1900.0   
6     3067.0       3.0       1.0  2.0     120.0         142.0     2014.0   
11    3067.0       4.0       2.0  0.0     245.0         210.0     1910.0   
14    3067.0       2.0       1.0  2.0     256.0         107.0     1890.0   

    CouncilArea  Lattitude  Longtitude  Regionname  Propertycount  
2            31   -37.8079    144.9934           2         4019.0  
4            31   -37.8093    144.9944           2         4019.0  
6            31   -37.8072    144.9941           2         4019.0  
11           31   -37.8024    144.9993           2         4019.0  
14           31   -37.8060    144.9954           2         4019.0

In [38]:
feat_df['Date'] = pd.to_datetime(feat_df['Date'], infer_datetime_format=True)
feat_df['Date'] = feat_df['Date'].astype(np.int64)
feat_df.head()

Suburb  Address  Rooms  Type  Method  SellerG                 Date  \
2        0     3922      2     0       1       22  1459555200000000000   
4        0     6458      3     0       3       22  1491177600000000000   
6        0     6960      4     0       4      147  1459900800000000000   
11       0     1374      3     0       1      147  1467676800000000000   
14       0     8740      2     0       1      147  1470787200000000000   

    Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  \
2        2.5    3067.0       2.0       1.0  0.0     156.0          79.0   
4        2.5    3067.0       3.0       2.0  0.0     134.0         150.0   
6        2.5    3067.0       3.0       1.0  2.0     120.0         142.0   
11       2.5    3067.0       4.0       2.0  0.0     245.0         210.0   
14       2.5    3067.0       2.0       1.0  2.0     256.0         107.0   

    YearBuilt  CouncilArea  Lattitude  Longtitude  Regionname  Propertycount  
2      1900.0           31   -37.8079    144.9934           2         4019.0  
4      1900.0           31   -37.8093    144.9944           2         4019.0  
6      2014.0           31   -37.8072    144.9941           2         4019.0  
11     1910.0           31   -37.8024    144.9993           2         4019.0  
14     1890.0           31   -37.8060    144.9954           2         4019.0

In [39]:
rf = RandomForestRegressor()
rf.fit(feat_df, y)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [40]:
from sklearn.model_selection import train_test_split

In [82]:
? train_test_split

In [42]:
p = train_test_split(feat_df, y)

In [73]:
len(p)

4

In [119]:
type(feat_df)

pandas.core.frame.DataFrame

In [120]:
type(y)

range

In [132]:
feat_df.shape, y.shape

((8887, 20), (8887,))

In [79]:
X_train, X_test, y_train, y_test = train_test_split(feat_df, y, test_size = 0.25, random_state =17)

In [80]:
len(feat_df)

8887

In [81]:
feat_df.shape, X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8887, 20), (6665, 20), (2222, 20), (6665,), (2222,))

In [52]:
rf = RandomForestRegressor(n_estimators =1, random_state =17)
rf = RandomForestRegressor(random_state =17)
rf.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=17, verbose=0, warm_start=False)

In [53]:
rf.score(X_train, y_train)

0.95823765581347

In [54]:
rf.score(X_test, y_test)

0.795955816130085

In [55]:
rf.predict(X_test)

array([1178050., 1010750.,  865900., ..., 1120000.,  620400., 2322600.])

In [56]:
rf = RandomForestRegressor(random_state =17)
rf.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=17, verbose=0, warm_start=False)

In [57]:
rf.estimators_[0].predict(X_test)

array([1350000.,  786000.,  890000., ...,  854000.,  623500., 2700000.])

In [58]:
rf.estimators_[1].predict(X_test)

array([ 910000., 1220000.,  795000., ..., 1120000.,  560000., 1850000.])

In [59]:
rf.estimators_[2].predict(X_test)

array([1250000., 1140000.,  875000., ..., 1115000.,  680500., 2200000.])

In [60]:
rf.predict(X_test)

array([1178050., 1010750.,  865900., ..., 1120000.,  620400., 2322600.])

In [61]:
y_hat = rf.predict(X_test)

In [62]:
y_hat

array([1178050., 1010750.,  865900., ..., 1120000.,  620400., 2322600.])

In [63]:
y_test

array([ 981000.,  875000.,  700000., ...,  932000.,  572000., 2200000.])

In [64]:
y_hat.shape, y_test.shape

((2222,), (2222,))

In [65]:
((y_hat - y_test) ** 2).mean()

81644859305.96785

In [66]:
mse = ((y_hat - y_test) ** 2).mean()

In [67]:
rmse = np.sqrt(mse)

In [68]:
mse, rmse

(81644859305.96785, 285735.6458441401)

In [69]:
v = (y_hat - y_test.mean()) ** 2

In [70]:
score = 1 - mse / v
score

array([ -5.93635313, -22.60805021,  -0.96846219, ..., -31.08776554,
         0.59530196,   0.94800071])

In [83]:
import numpy as np

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [90]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
y

range(0, 5)

In [118]:
train_test_split(y, shuffle=True)

[[0, 3, 2], [4, 1]]

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=3)
X_train

array([[2, 3],
       [0, 1],
       [4, 5]])

In [115]:
? numpy.random

Object ` numpy.random` not found.
